lesson-2
DmitriyYar/react-gb pull request #2
Opened 2022-08-28 17:07 UTC by DmitriyYar

2022-08-28 18:27 UTC, TauViper commented on src/App.jsx
> +// import style from './App.module.css';
Закомментированные строки лучше убирать

2022-08-28 18:27 UTC, TauViper commented on src/components/Form/Form.module.css
> +  /* justify-content: space-between; */
Так же удалить

2022-08-28 20:08 UTC, AndreyOsipuk commented on src/components/Form/Form.jsx
> +      console.log('Заполните поля');
вряд ли пользователь будет смотреть в консоль

2022-08-28 20:08 UTC, AndreyOsipuk commented on src/components/Form/Form.jsx
> +    setTimeout(() => {
а где очистка таймаута?

2022-08-28 20:08 UTC, AndreyOsipuk commented on src/components/Form/Form.jsx
> +    if (isTyping) {
а смысл? таймер надо запускать, когда измениться количество сообщений

2022-08-28 20:08 UTC, AndreyOsipuk commented on src/components/Message/Message.jsx
> +export const Message = (props) => (
деструктуризируй пропсы

2022-08-31 11:30 UTC, DoneAlejandro requested changes

2022-08-31 11:30 UTC, DoneAlejandro commented on src/App.jsx
> +      <div>
лучше вынести излишнюю логику в отдельный компонент, App оставить презентационной компонентой

2022-12-04 07:58 UTC, merged